### PR TITLE
fix: remove positions from state when closed with reverse position

### LINKED ISSUE #1416: [AUDIT] Zero-Size Position Bug Distorts AMM Reserve/Short/Long Totals due to Erroneous DecreasePosition Flow Entry
* If you open a buy position then immediately open a sell position for the same amount (might be reachable in other ways), it's possible to enter the decreasePosition flow as the check at https://github.com/NibiruChain/nibiru/blob/d39099499d93c0d3ebdf3576f6cd937d6ea8d095/x/perp/v2/keeper/clearing_house.go#L223-L223 can pass (currentPositionNotional is fractionally larger) and you end up with a position with a size of 0. This position is then not saved due to the check at https://github.com/NibiruChain/nibiru/blob/d39099499d93c0d3ebdf3576f6cd937d6ea8d095/x/perp/v2/keeper/clearing_house.go#L564-L564, but the AMM is still updated as if it were saved (due to k.SwapQuoteAsset). This then messes up the reserve/short/long totals of the AMM:

### PR DESCRIPTION
**Pull request by matthiasmatt**
# Description

- fix #1416 

# Purpose

Why is this PR important?

### CODE REVIEW

**Review by Unique-Divine — COMMENTED** [review]
Is their margin returned by the reverse close? And, is the position guaranteed to be empty if it has 0 size?

File: x/perp/v2/keeper/clearing_house.go [hunk 1]
```diff
@@ -555,6 +555,11 @@ func (k Keeper) afterPositionUpdate(
 
 	if !positionResp.Position.Size_.IsZero() {
 		k.Positions.Insert(ctx, collections.Join(market.Pair, traderAddr), positionResp.Position)
+	} else {
+		if !positionResp.Position.Margin.IsZero() {
```
Comment (k-yang) [inline x/perp/v2/keeper/clearing_house.go:559]: Do we ever zero out the position's `margin`? I think we keep it there when we reverse a position.

**Review by k-yang — APPROVED** [review]
